services:
  backend:
    build: 
      context: ./backend
    env_file: 
      - .env
    ports:
      - 5000:5000
  frontend:
    build: 
      context: ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL}
    env_file: 
      - .env
    ports:
      - 3000:3000